### PR TITLE
luigi's mansion themed board

### PR DESCRIPTION
**Pull request by Artamone**
added a luigi's mansion themed board to use my luigi's mansion background

### CODE REVIEW

**Comment by Sophilautia** [comment]
So it's been a while since I've singed off on a PR, I wanna introduce some more checks for the author to sign off on before accepting a PR, so I'm gonna put a checklist in here for you to go over. You don't necessarily have to fill out all of these, but they will all need to be filled out before it can be accepted into a stable build of CSWT. They're vaguely sorted in order of importance.

- [x] Board passes validation script

- [x] Files are in correct folders

- [ ] All FRBs pass possible paths check (under 70 iirc)

- [ ] All paths are functioning as intended (including doors and yoshi lifts and magmalices)

- [ ] There is nowhere you can get stuck and cause a softlock (accounting for warp cards)

- [ ] All backstreet destinations are as intended

- [x] YAML is formatted correctly

- [x] YAML has author and changelog

- [ ] YAML has Author's URL (or doesn't have one if not wanted)

- [x] Files and folders have no special characters / spaces / capitalisations

- [x] Map icon is included, follows existing template, and is correctly implemented in yaml

- [ ] Thumbnails for each board state are included (check this to ensure they're up-to-date

- [x] Music is properly implemented and uploaded to server

- [ ] All looping music is looping, and all non-looping music isn't looping

- [x] There are exactly 64 venture cards

- [ ] Venture card 45 is inactive OR there are no arcade or take a break squares

- [ ] Venture card 125 is inactive OR there are no arcade or boon squares

- [ ] There's nowhere you can get stuck by randomly warping from venture card 83

- [ ] Max dice roll is below 10

- [ ] You can't travel between three sets of doors in one roll

IF max dice roll is 9:

- [ ] There are no doors.

IF max dice roll is 8:

- [ ] There are no two-way doors

- [ ] You can't travel between two sets of doors in one roll

IF max dice roll is 7:

- [ ] You can't travel between two sets of doors in one roll

- [ ] Venture card 87 is inactive

IF max dice roll is 6:

- [ ] Venture card 87 is inactive

- [ ] Venture card 115 is inactive

- [ ] Balloonport test has been completed on emulator OR console

- [ ] Balloonport test has been completed on console

- [ ] At least three full games of the board have been completed by CPUs (see gecko codes to help speed this up dramatically)

- [ ] A full game of the board has been played by humans

- [ ] All music has been tested and volumes are OK

**Comment by Sophilautia** [comment]
If you have any questions about these, let me know, I'd appreciate feedback on this process since it's my first time trying it really.

**Comment by Artamone** [comment]
> So it's been a while since I've singed off on a PR, I wanna introduce some more checks for the author to sign off on before accepting a PR, so I'm gonna put a checklist in here for you to go over. You don't necessarily have to fill out all of these, but they will all need to be filled out before it can be accepted into a stable build of CSWT. They're vaguely sorted in order of importance.
> 
> * [x]  Board passes validation script
> * [x]  Files are in correct folders
> * [x]  All FRBs pass possible paths check (under 70 iirc)
> * [x]  All paths are functioning as intended (including doors and yoshi lifts and magmalices)
> * [x]  There is nowhere you can get stuck and cause a softlock (accounting for warp cards & balloonports)
> * [x]  All backstreet destinations are as intended
> * [x]  YAML is formatted correctly
> * [x]  YAML has author and changelog
> * [x]  YAML has Author's URL (or doesn't have one if not wanted)
> * [x]  Files and folders have no special characters / spaces / capitalisations
> * [x]  Map icon is included, follows existing template, and is correctly implemented in yaml
> * [x]  Thumbnails for each board state are included (and they're accurate as of the latest versions of the frb files)
> * [x]  Music is properly implemented and uploaded to server
> * [x]  All looping music is looping, and all non-looping music isn't looping
> * [x]  There are exactly 64 venture cards
> * [x]  IF Venture card 45 is active, then there must be both an arcade & take a break square
> * [ ]  IF Venture card 125 is active, then there must be both an arcade & boon square
> * [x]  There's nowhere you can get stuck by randomly warping from venture card 83, OR venture card 83 is inactive
> * [x]  Max dice roll is below 10
> * [x]  You can't travel between three sets of doors in one roll
> 
> IF max dice roll is 9:
> 
> * [ ]  There are no doors.
> 
> IF max dice roll is 8:
> 
> * [x]  There are no two-way doors
> * [x]  You can't travel between two sets of doors in one roll
> 
> IF max dice roll is 7:
> 
> * [ ]  You can't travel between two sets of doors in one roll
> * [ ]  Venture card 87 is inactive
> 
> IF max dice roll is 6:
> 
> * [ ]  Venture card 87 is inactive
> * [ ]  Venture card 115 is inactive
> 
> * [ ]  Balloonport test has been completed on emulator OR console
> * [ ]  Balloonport test has been completed on console
> * [ ]  At least three full games of the board have been completed by CPUs (see gecko codes to help speed this up dramatically)
> * [ ]  A full game of the board has been played by humans
> * [x]  All music has been tested and volumes are OK

**Comment by Ennesan** [comment]
The background zip file and the background name specified in the yaml do not match, so we cannot build with this board included. Also, the music file that is set in yaml does not seem to be in the background zip file.
Please edit the background zip file.

**Comment by Sophilautia** [comment]
> The background zip file and the background name specified in the yaml do not match, so we cannot build with this board included. 

Oh, nice catch. @Artamone will need to fix this.

> Also, the music file that is set in yaml does not seem to be in the background zip file.

Hm, I just updated the music so it should be okay. There might be a cache issue.

**Comment by Sophilautia** [comment]
I have created an invalidation, so it should fix the caching issue. Can you confirm that the background file has the correct music files now? @Ennesan

**Comment by Ennesan** [comment]
スクリーンショット 2024-01-19 001526
I checked by editing the background zip file name and it does not seem to contain this file.

**Comment by Ennesan** [comment]
> 無効化を作成したので、キャッシュの問題は解決されるはずです。 バックグラウンド ファイルに正しい音楽ファイルが含まれていることを確認できますか? @Ennesan
I confirmed that it is up-to-date.
Please change the name of the background specified in the yaml file to "LuigisMansion".

**Comment by Ennesan** [comment]
Please rename the background zip file to "mansion.zip".

**Comment by Ennesan** [comment]
image
@Sophilautia Rename the cmpres file name and the scene file name to LuigisMansion and upload it to nikkums.io.

**Comment by Ennesan** [comment]
@Sophilautia 
Edited file to work correctly with background name LuigiMansion.
It has been tested and works correctly.
I am sending you a link to the zip file here.
https://drive.google.com/u/0/uc?id=1SF_UsA3-fuyxqsxU29DwgrUoOg9D5Ysb&export=download

**Comment by Ennesan** [comment]
@Artamone The board icon file name is the same as the Rainbow Road MKWii file name; when I build to include Rainbow Road MKWii and Luigi's Mansion, the icon is not the Luigi's Mansion icon. Therefore, please rename the file with the Luigi's Mansion icon. Also, remember to edit the mapicon part of the yaml to the new filename.

**Comment by Sophilautia** [comment]
I'm really confused... You said the zip file needed to have the scene and cmpres files renamed to LuigisMansion, but they already are. See here. 
image

**Comment by Sophilautia** [comment]
@Artamone This is just waiting on you to update the map icon names

**Comment by Artamone** [comment]
it should be good now

**Pull request merged**
