### PR TITLE
New map: StarshipRedux

### PR DESCRIPTION
**Pull request by FatCat67**

### CODE REVIEW

**Comment by Sophilautia** [comment]
Please remove "StarShip Mario.yaml" from your pull request, I'm assumning that file wasn't meant to be uploaded.

**Comment by Sophilautia** [comment]
Okay, it's passing validation now.

Could you please fill out our board submission form for this board:

https://forms.gle/yzqiYrQ4Munc44Lo7

**Comment by Sophilautia** [comment]
Okay, I've noticed a few issues.

1. The Title and Description of your board included superfluous languages that you didn't edit, so I removed them
2. I tidied up the formatting of the description to match the template
3. The music download you linked to is DelfinoRedux's music, it seems like you made a mistake here and will need to fix it

Also went and looked at MidgarT, and I've decided that it needs a bit more work before it's ready to be included in CSWT, so I removed it from your PR for now.

**Comment by Sophilautia** [comment]
Still waiting on @FatCat67 to fix the music here

**Comment by FatCat67** [comment]
whats up with the music??? if its about the 2nd link ive never done that
myself so idk where to get that from, if there's another issue ill fix it

**Comment by Sophilautia** [comment]
@FatCat67 The link to the music download in the yaml (https://drive.google.com/uc?export=download&id=1C24uC2iPDPojTfbJA8iO0LtuTjp17k_I) links to Delfino Redux music. I don't have a link to the music of this board.

**Comment by FatCat67** [comment]
just fixed that, my bad

**Comment by Sophilautia** [comment]
Thanks for that.

I checked the music and the sample rate was higher than 32k, so I've reduced the sample rate for the tracks and uploaded them to the server. Please make sure to use 32k music in the future!

**Comment by Sophilautia** [comment]
@FatCat67 

I did a verification and found some more issues. Sorry for the trouble.

1. An author isn't specified in the yaml
2. A changelog isn't specified in the yaml
3. The yaml doesn't define a mapIcon
4. Max Dice Roll is set to 6, but Venture Card 87 is enabled. Venture Card 87 makes the player roll either a 7 or an 8, which can work, but can also cause issues since this value being higher than the Max Dice Roll makes it very hard to test pathing for.

I went and addressed 1-3 by adding a changelog section, defining the mapIcon, and adding an author section attributing the board to FatCat67. If you'd like to add a URL for your attribution please let me know.

As for point 4 though, this will need your input on which venture card you'd like to replace 87 with.

**Pull request merged**
