### PR TITLE
New map time clock

### PR DESCRIPTION
**Pull request by ormaq**
Cool time clock board

### CODE REVIEW

**Comment by ormaq** [comment]
ezgif-1-832109449e

**Comment by Sophilautia** [comment]
2 Issues Found that need fixing:

The value of baseSalary is 300 in the yaml file but 250 in the frb file.
The value of salaryIncrement is 250 in the yaml file but 200 in the frb file.

This is an interesting board! hough the title and description are a bit bland. Is English not your native language? We might be able to help give it a better name and title.

Also, the four corners seem a little unbalanced. Perhaps #79 could be changed to a Boon Square, and #21 could be changed to a Take-a-Break Square?

**Comment by ormaq** [comment]
Hello there, I have updated the Yaml and files to be correct for the bank values, as well I made some changes to the map after playing it a few times. This should make the map much more fair and decision based. There is also a better description and some other minor changes. Enjoy

**Comment by ormaq** [comment]
ezgif-2-e5d0745c39

New Gif!

**Comment by Sophilautia** [comment]
Oh that's an easy fix. We just change the background to bg001_clean. I'll do it now.

**Pull request merged**
