### PR TITLE
New Map: Pac-Man FS

### PR DESCRIPTION
**Pull request by L1N3R1D3R**
My first ever custom board. Hopefully it doesn't suck too badly! _(Ignore those first two commits.)_

### CODE REVIEW

**Comment by Sophilautia** [comment]
Hello @L1N3R1D3R, can you please complete out the board submission form: https://forms.gle/NjmRxoW8ESf8mUKK8

**Comment by L1N3R1D3R** [comment]
Oh, you do that before it gets accepted here? I thought the question "Has a full game of this board been played by humans?" meant that it would have to be tested by other community members first. I could play this with other people, but not for a couple days, and we don't play as optimally as you guys. I guess I'll just finish the CPU testing and call it there.

**Comment by L1N3R1D3R** [comment]
Submitted the form.

**Comment by Sophilautia** [comment]
I noticed the yaml has 65 venture cards active, you need to deactivate one

**Comment by Sophilautia** [comment]
Did you actually do the orange dice validation? You wrote that you did, but I don't see any records of it on the discord

**Comment by Sophilautia** [comment]
Made some mistakes, so don't mind those if you got any notifications. This looks all good as far as I can tell! I'll merge it and have it added to CSWT-Test

**Pull request merged**
