### PR TITLE
Star Carnival, Magmalice Mine, and Spooky Hallow

### PR DESCRIPTION
**Pull request by McKrak**
This pull request contains two new maps:
-Star Carnival, from Mario Party 8. Comes with a custom background.
-Magmalice Mine, based on Magma Mine from Mario Party 9. Comes with a custom background that moves between board states.

It also contains an additional background, Spooky Hollow, from Pac-Man Party. It does not have a board associated with it yet, as it still needs work that I have to put in.

### CODE REVIEW

**Comment by phellen007** [comment]
I approve of this pull request for Magmalice Mine.

**Comment by Ennesan** [comment]
Dear nikkums and Sophilautia. Please do not merge this pull request yet. Board and background are not complete.

**Comment by Sophilautia** [comment]
Noted 👍

**Comment by nikkiwritescode** [comment]
I've set this PR as a draft so it doesn't accidentally get merged in. Feel free to set it back to Ready for Review when you're ready for us to take a look at it!

**Comment by McKrak** [comment]
A new PR will be made for each individual map when it is finished.

**Pull request closed without merging**
