### PR TITLE
Map fixes and updates

### PR DESCRIPTION
**Pull request by phellen007**
Fix for a soft lock that happened in Slime guys, and overhaul/update to Turtle Fortress

### CODE REVIEW

**Comment by Sophilautia** [comment]
Can you please complete this checklist to the best of your ability for each of the changed boards:

- [x] Board passes validation script

- [x] Files are in correct folders

- [ ] All FRBs pass possible paths check (under 70 iirc)

- [ ] All paths are functioning as intended (including doors and yoshi lifts and magmalices)

- [ ] There is nowhere you can get stuck and cause a softlock (accounting for warp cards & balloonports)

- [ ] All backstreet destinations are as intended

- [x] YAML is formatted correctly

- [x] YAML has author and changelog

- [ ] YAML has Author's URL (or doesn't have one if not wanted)

- [x] Files and folders have no special characters / spaces / capitalisations

- [ ] Map icon is included, follows existing template, and is correctly implemented in yaml

- [ ] Thumbnails for each board state are included (and they're accurate as of the latest versions of the frb files)

- [ ] Music is properly implemented and uploaded to server

- [ ] All looping music is looping, and all non-looping music isn't looping

- [ ] There are exactly 64 venture cards

- [ ] IF Venture card 45 is active, then there must be both an arcade & take a break square

- [ ] IF Venture card 125 is active, then there must be both an arcade & boon square

- [ ] There's nowhere you can get stuck by randomly warping from venture card 83, OR venture card 83 is inactive

- [ ] Max dice roll is below 10

- [ ] You can't travel between three sets of doors in one roll

---

IF max dice roll is 9:

- [ ] There are no doors.

---

IF max dice roll is 8:

- [ ] There are no two-way doors

- [ ] You can't travel between two sets of doors in one roll

---

IF max dice roll is 7:

- [ ] You can't travel between two sets of doors in one roll

- [ ] Venture card 87 is inactive

---

IF max dice roll is 6:

- [ ] Venture card 87 is inactive

- [ ] Venture card 115 is inactive

---

- [ ] Balloonport test has been completed on emulator OR console

- [ ] Balloonport test has been completed on console

- [ ] At least three full games of the board have been completed by CPUs (see gecko codes to help speed this up dramatically)

- [ ] A full game of the board has been played by humans

- [ ] All music has been tested and volumes are OK

**Comment by phellen007** [comment]
Only thing that isnt checked for all of these yet is running 3 games with npcs

**Comment by phellen007** [comment]
Super Bowser's Trackway
> 
> * [x]  Board passes validation script
> * [x]  Files are in correct folders
> * [x]  All FRBs pass possible paths check (under 70 iirc)
> * [x]  All paths are functioning as intended (including doors and yoshi lifts and magmalices)
> * [x]  There is nowhere you can get stuck and cause a softlock (accounting for warp cards & balloonports)
> * [x]  All backstreet destinations are as intended
> * [x]  YAML is formatted correctly
> * [x]  YAML has author and changelog
> * [x]  YAML has Author's URL (or doesn't have one if not wanted)
> * [x]  Files and folders have no special characters / spaces / capitalisations
> * [x]  Map icon is included, follows existing template, and is correctly implemented in yaml
> * [x]  Thumbnails for each board state are included (and they're accurate as of the latest versions of the frb files)
> * [x]  Music is properly implemented and uploaded to server
> * [x]  All looping music is looping, and all non-looping music isn't looping
> * [x]  There are exactly 64 venture cards
> * [x]  IF Venture card 45 is active, then there must be both an arcade & take a break square
> * [x]  IF Venture card 125 is active, then there must be both an arcade & boon square
> * [x]  There's nowhere you can get stuck by randomly warping from venture card 83, OR venture card 83 is inactive
> * [x]  Max dice roll is below 10
> * [x]  You can't travel between three sets of doors in one roll
> 
> IF max dice roll is 9:
> 
> * [x]  There are no doors.
> 
> IF max dice roll is 8:
> 
> * [x]  There are no two-way doors
> * [x]  You can't travel between two sets of doors in one roll
> 
> IF max dice roll is 7:
> 
> * [x]  You can't travel between two sets of doors in one roll
> * [x]  Venture card 87 is inactive
> 
> IF max dice roll is 6:
> 
> * [x]  Venture card 87 is inactive
> * [x]  Venture card 115 is inactive
> 
> * [x]  Balloonport test has been completed on emulator OR console
> * [ ]  Balloonport test has been completed on console
> * [x]  At least three full games of the board have been completed by CPUs (see gecko codes to help speed this up dramatically)
> * [x]  A full game of the board has been played by humans
> * [x]  All music has been tested and volumes are OK

**Comment by phellen007** [comment]
Castaway Bay Cside
> 
> > * [x]   Board passes validation script
> > * [x]   Files are in correct folders
> > * [x]   All FRBs pass possible paths check (under 70 iirc)
> > * [x]   All paths are functioning as intended (including doors and yoshi lifts and magmalices)
> > * [x]   There is nowhere you can get stuck and cause a softlock (accounting for warp cards & balloonports)
> > * [x]   All backstreet destinations are as intended
> > * [x]   YAML is formatted correctly
> > * [x]   YAML has author and changelog
> > * [x]   YAML has Author's URL (or doesn't have one if not wanted)
> > * [x]   Files and folders have no special characters / spaces / capitalisations
> > * [x]   Map icon is included, follows existing template, and is correctly implemented in yaml
> > * [x]   Thumbnails for each board state are included (and they're accurate as of the latest versions of the frb files)
> > * [x]   Music is properly implemented and uploaded to server
> > * [x]   All looping music is looping, and all non-looping music isn't looping
> > * [x]   There are exactly 64 venture cards
> > * [x]   IF Venture card 45 is active, then there must be both an arcade & take a break square
> > * [x]   IF Venture card 125 is active, then there must be both an arcade & boon square
> > * [x]   There's nowhere you can get stuck by randomly warping from venture card 83, OR venture card 83 is inactive
> > * [x]   Max dice roll is below 10
> > * [x]   You can't travel between three sets of doors in one roll
> > 
> > IF max dice roll is 9:
> > 
> > * [x]   There are no doors.
> > 
> > IF max dice roll is 8:
> > 
> > * [x]   There are no two-way doors
> > * [x]   You can't travel between two sets of doors in one roll
> > 
> > IF max dice roll is 7:
> > 
> > * [x]   You can't travel between two sets of doors in one roll
> > * [x]   Venture card 87 is inactive
> > 
> > IF max dice roll is 6:
> > 
> > * [x]   Venture card 87 is inactive
> > * [x]   Venture card 115 is inactive
> > * [x]   Balloonport test has been completed on emulator OR console
> > * [ ]   Balloonport test has been completed on console
> > * [x]   At least three full games of the board have been completed by CPUs (see gecko codes to help speed this up dramatically)
> > * [x]   A full game of the board has been played by humans
> > * [x]   All music has been tested and volumes are OK

**Comment by Ennesan** [comment]
Castaway Bay - CSide, but if there is more than one author on the board, please split it into multiple lines.

**Comment by phellen007** [comment]
> Slime Guys Payday Express
> 
> > > * [x]    Board passes validation script
> > > * [x]    Files are in correct folders
> > > * [x]    All FRBs pass possible paths check (under 70 iirc)
> > > * [x]    All paths are functioning as intended (including doors and yoshi lifts and magmalices)
> > > * [x]    There is nowhere you can get stuck and cause a softlock (accounting for warp cards & balloonports)
> > > * [x]    All backstreet destinations are as intended
> > > * [x]    YAML is formatted correctly
> > > * [x]    YAML has author and changelog
> > > * [x]    YAML has Author's URL (or doesn't have one if not wanted)
> > > * [x]    Files and folders have no special characters / spaces / capitalisations
> > > * [x]    Map icon is included, follows existing template, and is correctly implemented in yaml
> > > * [x]    Thumbnails for each board state are included (and they're accurate as of the latest versions of the frb files)
> > > * [x]    Music is properly implemented and uploaded to server
> > > * [x]    All looping music is looping, and all non-looping music isn't looping
> > > * [x]    There are exactly 64 venture cards
> > > * [x]    IF Venture card 45 is active, then there must be both an arcade & take a break square
> > > * [x]    IF Venture card 125 is active, then there must be both an arcade & boon square
> > > * [x]    There's nowhere you can get stuck by randomly warping from venture card 83, OR venture card 83 is inactive
> > > * [x]    Max dice roll is below 10
> > > * [x]    You can't travel between three sets of doors in one roll
> > > 
> > > IF max dice roll is 9:
> > > 
> > > * [x]    There are no doors.
> > > 
> > > IF max dice roll is 8:
> > > 
> > > * [x]    There are no two-way doors
> > > * [x]    You can't travel between two sets of doors in one roll
> > > 
> > > IF max dice roll is 7:
> > > 
> > > * [x]    You can't travel between two sets of doors in one roll
> > > * [x]    Venture card 87 is inactive
> > > 
> > > IF max dice roll is 6:
> > > 
> > > * [x]    Venture card 87 is inactive
> > > * [x]    Venture card 115 is inactive
> > > * [x]    Balloonport test has been completed on emulator OR console
> > > * [ ]    Balloonport test has been completed on console
> > > * [x]    At least three full games of the board have been completed by CPUs (see gecko codes to help speed this up dramatically)
> > > * [x]    A full game of the board has been played by humans
> > > * [x]    All music has been tested and volumes are OK

**Comment by phellen007** [comment]
> Castaway Bay - CSide, but if there is more than one author on the board, please split it into multiple lines.

Thanks, I fixed this and resent the PR

**Comment by phellen007** [comment]
> Turtle Fortress
> 
> > * [x]   Board passes validation script
> > * [x]   Files are in correct folders
> > * [x]   All FRBs pass possible paths check (under 70 iirc)
> > * [x]   All paths are functioning as intended (including doors and yoshi lifts and magmalices)
> > * [x]   There is nowhere you can get stuck and cause a softlock (accounting for warp cards & balloonports)
> > * [x]   All backstreet destinations are as intended
> > * [x]   YAML is formatted correctly
> > * [x]   YAML has author and changelog
> > * [x]   YAML has Author's URL (or doesn't have one if not wanted)
> > * [x]   Files and folders have no special characters / spaces / capitalisations
> > * [x]   Map icon is included, follows existing template, and is correctly implemented in yaml
> > * [x]   Thumbnails for each board state are included (and they're accurate as of the latest versions of the frb files)
> > * [x]   Music is properly implemented and uploaded to server
> > * [x]   All looping music is looping, and all non-looping music isn't looping
> > * [x]   There are exactly 64 venture cards
> > * [x]   IF Venture card 45 is active, then there must be both an arcade & take a break square
> > * [x]   IF Venture card 125 is active, then there must be both an arcade & boon square
> > * [x]   There's nowhere you can get stuck by randomly warping from venture card 83, OR venture card 83 is inactive
> > * [x]   Max dice roll is below 10
> > * [x]   You can't travel between three sets of doors in one roll
> > 
> > IF max dice roll is 9:
> > 
> > * [x]   There are no doors.
> > 
> > IF max dice roll is 8:
> > 
> > * [x]   There are no two-way doors
> > * [x]   You can't travel between two sets of doors in one roll
> > 
> > IF max dice roll is 7:
> > 
> > * [x]   You can't travel between two sets of doors in one roll
> > * [x]   Venture card 87 is inactive
> > 
> > IF max dice roll is 6:
> > 
> > * [x]   Venture card 87 is inactive
> > * [x]   Venture card 115 is inactive
> > * [x]   Balloonport test has been completed on emulator OR console
> > * [ ]   Balloonport test has been completed on console
> > * [x]   At least three full games of the board have been completed by CPUs (see gecko codes to help speed this up dramatically)
> > * [x]   A full game of the board has been played by humans
> > * [x]   All music has been tested and volumes are OK

**Comment by phellen007** [comment]
> > Fortunapolis
> > > * [x]    Board passes validation script
> > > * [x]    Files are in correct folders
> > > * [x]    All FRBs pass possible paths check (under 70 iirc)
> > > * [x]    All paths are functioning as intended (including doors and yoshi lifts and magmalices)
> > > * [x]    There is nowhere you can get stuck and cause a softlock (accounting for warp cards & balloonports)
> > > * [x]    All backstreet destinations are as intended
> > > * [x]    YAML is formatted correctly
> > > * [x]    YAML has author and changelog
> > > * [x]    YAML has Author's URL (or doesn't have one if not wanted)
> > > * [x]    Files and folders have no special characters / spaces / capitalisations
> > > * [x]    Map icon is included, follows existing template, and is correctly implemented in yaml
> > > * [x]    Thumbnails for each board state are included (and they're accurate as of the latest versions of the frb files)
> > > * [x]    Music is properly implemented and uploaded to server
> > > * [x]    All looping music is looping, and all non-looping music isn't looping
> > > * [x]    There are exactly 64 venture cards
> > > * [x]    IF Venture card 45 is active, then there must be both an arcade & take a break square
> > > * [x]    IF Venture card 125 is active, then there must be both an arcade & boon square
> > > * [x]    There's nowhere you can get stuck by randomly warping from venture card 83, OR venture card 83 is inactive
> > > * [x]    Max dice roll is below 10
> > > * [x]    You can't travel between three sets of doors in one roll
> > > 
> > > IF max dice roll is 9:
> > > 
> > > * [x]    There are no doors.
> > > 
> > > IF max dice roll is 8:
> > > 
> > > * [x]    There are no two-way doors
> > > * [x]    You can't travel between two sets of doors in one roll
> > > 
> > > IF max dice roll is 7:
> > > 
> > > * [x]    You can't travel between two sets of doors in one roll
> > > * [x]    Venture card 87 is inactive
> > > 
> > > IF max dice roll is 6:
> > > 
> > > * [x]    Venture card 87 is inactive
> > > * [x]    Venture card 115 is inactive
> > > * [x]    Balloonport test has been completed on emulator OR console
> > > * [ ]    Balloonport test has been completed on console
> > > * [x]    At least three full games of the board have been completed by CPUs (see gecko codes to help speed this up dramatically)
> > > * [x]    A full game of the board has been played by humans
> > > * [x]    All music has been tested and volumes are OK

**Comment by phellen007** [comment]
> Fortune Gate
> 
> > * [x]   Board passes validation script
> > * [x]   Files are in correct folders
> > * [x]   All FRBs pass possible paths check (under 70 iirc)
> > * [x]   All paths are functioning as intended (including doors and yoshi lifts and magmalices)
> > * [x]   There is nowhere you can get stuck and cause a softlock (accounting for warp cards & balloonports)
> > * [x]   All backstreet destinations are as intended
> > * [x]   YAML is formatted correctly
> > * [x]   YAML has author and changelog
> > * [x]   YAML has Author's URL (or doesn't have one if not wanted)
> > * [x]   Files and folders have no special characters / spaces / capitalisations
> > * [x]   Map icon is included, follows existing template, and is correctly implemented in yaml
> > * [x]   Thumbnails for each board state are included (and they're accurate as of the latest versions of the frb files)
> > * [x]   Music is properly implemented and uploaded to server
> > * [x]   All looping music is looping, and all non-looping music isn't looping
> > * [x]   There are exactly 64 venture cards
> > * [x]   IF Venture card 45 is active, then there must be both an arcade & take a break square
> > * [x]   IF Venture card 125 is active, then there must be both an arcade & boon square
> > * [x]   There's nowhere you can get stuck by randomly warping from venture card 83, OR venture card 83 is inactive
> > * [x]   Max dice roll is below 10
> > * [x]   You can't travel between three sets of doors in one roll
> > 
> > IF max dice roll is 9:
> > 
> > * [x]   There are no doors.
> > 
> > IF max dice roll is 8:
> > 
> > * [x]   There are no two-way doors
> > * [x]   You can't travel between two sets of doors in one roll
> > 
> > IF max dice roll is 7:
> > 
> > * [x]   You can't travel between two sets of doors in one roll
> > * [x]   Venture card 87 is inactive
> > 
> > IF max dice roll is 6:
> > 
> > * [x]   Venture card 87 is inactive
> > * [x]   Venture card 115 is inactive
> > * [x]   Balloonport test has been completed on emulator OR console
> > * [ ]   Balloonport test has been completed on console
> > * [x]   At least three full games of the board have been completed by CPUs (see gecko codes to help speed this up dramatically)
> > * [x]   A full game of the board has been played by humans
> > * [x]   All music has been tested and volumes are OK

**Pull request merged**
