### PR TITLE
Map Updates: Playground and Crossroads

### PR DESCRIPTION
**Pull request by Giftshaven**
Playground:
Removed the two vacants.

Crossroads:
Increased target amount (18000 → 20000)
Rearranged spaces. Now the bank is in the middle.
Pathing changes. Players can travel through the middle with more freedom if they want to go up or down.

### CODE REVIEW

**Comment by Sophilautia** [comment]
Found 2 issues in Crossroads:
The value of initialCash is 1800 in the yaml file but 2000 in the frb file.
The value of salaryIncrement is 150 in the yaml file but 200 in the frb file.

**Comment by Sophilautia** [comment]
Playground map hasn't been modified.
Venn Diagram has.

Both the Playground and Venn Diagram yamls have improper formatting and inaccurate/missing changelogs.

**Comment by Neazi** [comment]
プルリクエストの内容を確認し、私のリポジトリの方でこれら3つのボードの更新を適用しました。
なお、Crossroadsにおいては、変更ログがv2になっているのに、更新前のfrbがv2になっていないということが発生していました。今回の更新により、変更ログはv3にしていないのでご了承ください。

I have reviewed the pull request and applied the updates to these three boards in my repository.
Please note that in Crossroads, the change log was set to v2, but the frb was not set to v2 before the update. Please note that the change log is not v3 as a result of this update.

**Comment by Sophilautia** [comment]
Merged manually in https://github.com/FortuneStreetModding/fortunestreetmodding.github.io/pull/133

**Pull request closed without merging**
