### PR TITLE
V4 of Turtle Fortress

### PR DESCRIPTION
**Pull request by phellen007**
Added changes suggested in the reviews to Turtle Fortress

### CODE REVIEW

**Comment by Ennesan** [comment]
Sophilautiaは、プルリクエストをマージする前に空白文字のあるFortune Gate FG1ディレクトリを削除してください。

**Comment by Ennesan** [comment]
Sophilautia should delete the Fortune Gate FG1 directory with whitespace before merging the pull request.

**Comment by phellen007** [comment]
Hey Sophilautia, Let me know if there's anything I can do or still need to do for the files to be able to pass the board validation. Thanks

**Comment by Sophilautia** [comment]
There were a couple of duplicate folders I had to remove, and a capitalisation error, but otherwise it seems good!

**Pull request merged**
