### PR TITLE
Add board and background 'King Boo's Haunted Hideaway'

### PR DESCRIPTION
**Pull request by McKrak**
Revision of King Boo's Haunted Hideaway is done. Ready for submission.

### CODE REVIEW

**Comment by phellen007** [comment]
In the yaml the authors names have to each be on their own lines, for the fortune street modding site. Like this...

Name: Mckrak
Name: phellen007

**Comment by Sophilautia** [comment]
Can you please complete this checklist to the best of your ability for the new board:

- [x] Board passes validation script

- [x] Files are in correct folders

- [ ] All FRBs pass possible paths check (under 70 iirc)

- [ ] All paths are functioning as intended (including doors and yoshi lifts and magmalices)

- [ ] There is nowhere you can get stuck and cause a softlock (accounting for warp cards & balloonports)

- [ ] All backstreet destinations are as intended

- [x] YAML is formatted correctly

- [x] YAML has author and changelog

- [ ] YAML has Author's URL (or doesn't have one if not wanted)

- [x] Files and folders have no special characters / spaces / capitalisations (I've verified that capitalisation seems to be consistent so this should be fine)

- [ ] Map icon is included, follows existing template, and is correctly implemented in yaml

- [ ] Thumbnails for each board state are included (and they're accurate as of the latest versions of the frb files)

- [ ] Music is properly implemented and uploaded to server

- [ ] All looping music is looping, and all non-looping music isn't looping

- [x] There are exactly 64 venture cards

- [ ] IF Venture card 45 is active, then there must be both an arcade & take a break square

- [ ] IF Venture card 125 is active, then there must be both an arcade & boon square

- [ ] There's nowhere you can get stuck by randomly warping from venture card 83, OR venture card 83 is inactive

- [ ] Max dice roll is below 10

- [ ] You can't travel between three sets of doors in one roll

---

IF max dice roll is 9:

- [ ] There are no doors.

---

IF max dice roll is 8:

- [ ] There are no two-way doors

- [ ] You can't travel between two sets of doors in one roll

---

IF max dice roll is 7:

- [ ] You can't travel between two sets of doors in one roll

- [ ] Venture card 87 is inactive

---

IF max dice roll is 6:

- [ ] Venture card 87 is inactive

- [ ] Venture card 115 is inactive

---

- [ ] Balloonport test has been completed on emulator OR console

- [ ] Balloonport test has been completed on console

- [ ] At least three full games of the board have been completed by CPUs (see gecko codes to help speed this up dramatically)

- [ ] A full game of the board has been played by humans

- [ ] All music has been tested and volumes are OK

**Comment by Sophilautia** [comment]
KBHH.background.zip has been uploaded to nikkums.io

**Comment by phellen007** [comment]
> King Boo's Haunted Hideaway
> 
> * [x]  Board passes validation script
> * [x]  Files are in correct folders
> * [x]  All FRBs pass possible paths check (under 70 iirc)
> * [x]  All paths are functioning as intended (including doors and yoshi lifts and magmalices)
> * [x]  There is nowhere you can get stuck and cause a softlock (accounting for warp cards & balloonports)
> * [x]  All backstreet destinations are as intended
> * [x]  YAML is formatted correctly
> * [x]  YAML has author and changelog
> * [x]  YAML has Author's URL (or doesn't have one if not wanted)
> * [x]  Files and folders have no special characters / spaces / capitalisations (I've verified that capitalisation seems to be consistent so this should be fine)
> * [x]  Map icon is included, follows existing template, and is correctly implemented in yaml
> * [x]  Thumbnails for each board state are included (and they're accurate as of the latest versions of the frb files)
> * [x]  Music is properly implemented and uploaded to server
> * [x]  All looping music is looping, and all non-looping music isn't looping
> * [x]  There are exactly 64 venture cards
> * [x]  IF Venture card 45 is active, then there must be both an arcade & take a break square
> * [x]  IF Venture card 125 is active, then there must be both an arcade & boon square
> * [x]  There's nowhere you can get stuck by randomly warping from venture card 83, OR venture card 83 is inactive
> * [x]  Max dice roll is below 10
> * [x]  You can't travel between three sets of doors in one roll
> 
> IF max dice roll is 9:
> 
> * [x]  There are no doors.
> 
> IF max dice roll is 8:
> 
> * [x]  There are no two-way doors
> * [x]  You can't travel between two sets of doors in one roll
> 
> IF max dice roll is 7:
> 
> * [x]  You can't travel between two sets of doors in one roll
> * [x]  Venture card 87 is inactive
> 
> IF max dice roll is 6:
> 
> * [x]  Venture card 87 is inactive
> * [x]  Venture card 115 is inactive
> 
> * [x]  Balloonport test has been completed on emulator OR console
> * [x]  Balloonport test has been completed on console
> * [x]  At least three full games of the board have been completed by CPUs (see gecko codes to help speed this up dramatically)
> * [x]  A full game of the board has been played by humans
> * [x]  All music has been tested and volumes are OK

**Comment by phellen007** [comment]
Mckrak mentioned having successfully tested the balloons on console earlier so I checked it off in the list.

**Pull request merged**
