### PR TITLE
Tick tock trader update

### PR DESCRIPTION
**Pull request by ormaq**
Updated :)

I reduced the map size significantly and changed the warp pad's to doors so that you can choose your path more freely 

as well the districts are much smaller and more varied

also the map design is more simple, there is less overall paths to take in the mid sections

### CODE REVIEW

**Comment by Ennesan** [comment]
frbファイルとyamlファイルのMaxDiceRollを6に変更してください。これが8だと特定の操作を行ったときにクラッシュが発生するので、それを防ぐために変更が必要です。

**Comment by Ennesan** [comment]
Change the MaxDiceRoll in the frb and yaml files to 6. If this is 8, a crash will occur when certain operations are performed, and the change is necessary to prevent this.

**Comment by Sophilautia** [comment]
Got another error. The value of maxDiceRoll is 6 in the yaml file but 8 in the frb file.

Also as far as I can tell that's the only thing that was changed in the final update? The description mentioned other changes but I don't see any.

**Comment by ormaq** [comment]
Whoops for some reason the branch did not push updating now

**Comment by Sophilautia** [comment]
It's been a while since I looked at this, but I think it's all been tested for any issues? I'll merge the update for now and let the testers take it from here.

**Pull request merged**
